[2023-04-28T22:22:50.504+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: booking_ingestion_DAG.extract_data manual__2023-04-28T22:22:49.390136+00:00 [queued]>
[2023-04-28T22:22:50.517+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: booking_ingestion_DAG.extract_data manual__2023-04-28T22:22:49.390136+00:00 [queued]>
[2023-04-28T22:22:50.518+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T22:22:50.519+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-28T22:22:50.520+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-28T22:22:50.537+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): extract_data> on 2023-04-28 22:22:49.390136+00:00
[2023-04-28T22:22:50.541+0000] {standard_task_runner.py:55} INFO - Started process 5668 to run task
[2023-04-28T22:22:50.544+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'booking_ingestion_DAG', 'extract_data', 'manual__2023-04-28T22:22:49.390136+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpamcbf7e1']
[2023-04-28T22:22:50.547+0000] {standard_task_runner.py:83} INFO - Job 60: Subtask extract_data
[2023-04-28T22:22:50.669+0000] {task_command.py:389} INFO - Running <TaskInstance: booking_ingestion_DAG.extract_data manual__2023-04-28T22:22:49.390136+00:00 [running]> on host 0e14e6a5e88f
[2023-04-28T22:22:50.941+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=booking_ingestion_DAG
AIRFLOW_CTX_TASK_ID=extract_data
AIRFLOW_CTX_EXECUTION_DATE=2023-04-28T22:22:49.390136+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-28T22:22:49.390136+00:00
[2023-04-28T22:22:50.961+0000] {python.py:177} INFO - Done. Returned value was: {'booking':     client_id booking_date          room_type  hotel_id  booking_cost currency
0           4   2016/11/02  first_class_2_bed         6        3140.0      GBP
1           2   2017-07-13      balcony_2_bed         2        2325.0      EUR
2           3   2017-10-17     standard_3_bed         6        2475.0      EUR
3           3   2018-01-16     standard_1_bed         4           NaN      NaN
4           1   2018/03/20      balcony_2_bed         1        2740.0      GBP
5           2   2019-10-10     standard_2_bed         5        1760.0      GBP
6           5   2019-12-24     standard_2_bed         3        4000.0      GBP
7           6   2019/09/14  first_class_2_bed         2        1840.0      GBP
8           4   2019-08-07  first_class_2_bed         1        2910.0      GBP
9           2   2020-08-07  first_class_2_bed         1        2910.0      GBP
10          3   2020-08-07  first_class_2_bed         1        2910.0      GBP
11          2   2021-08-07     standard_1_bed         1        2910.0      GBP
12          4   2021-08-07     standard_1_bed         1        2910.0      GBP
13          5   2021-08-07     standard_1_bed         1        2910.0      GBP, 'client':    client_id   age      name      type
0          1   NaN       Ann  standard
1          2  38.0       Ben  standard
2          3  30.0       Tom  standard
3          4  43.0    Bianca       VIP
4          5  49.0  Caroline  standard
5          6  28.0      Kate       VIP, 'hotel':    hotel_id                     name   address
0         1             Astro Resort  address1
1         2            Dream Connect  address2
2         3              Green Acres  address3
3         4  Millennium Times Square  address5
4         5          The Clift Royal  address5
5         6             The New View  address6}
[2023-04-28T22:22:50.997+0000] {xcom.py:635} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-04-28T22:22:51.001+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2305, in xcom_push
    session=session,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 72, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 240, in set
    map_index=map_index,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/xcom.py", line 627, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 176, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/json.py", line 170, in default
    return super().default(o)
  File "/usr/local/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-04-28T22:22:51.023+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=booking_ingestion_DAG, task_id=extract_data, execution_date=20230428T222249, start_date=20230428T222250, end_date=20230428T222251
[2023-04-28T22:22:51.058+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 60 for task extract_data (Object of type DataFrame is not JSON serializable; 5668)
[2023-04-28T22:22:51.079+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-28T22:22:51.173+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
